var BeaverType = [
    {
    	type:0,
    	desplazamiento:20,
    	strench:10,
    	speed:10,
    	armor:10,
    	lives:3,
    	textureName:s_Castorcete,
		frameName:"castor.png",
		imageInit:["castor.png","castor1.png"],
		imageUp:["castor2.png","castor3.png"],
		imageDown:["castor6.png","castor7.png"],
		imageRotate:["castor5.png","castor.png","castor4.png","castor5.png"]
    },
    {
    	type:1,
    	desplazamiento:20,
    	strench:50,
    	speed:10,
    	armor:10,
    	lives:3,
    	textureName:s_Castorcete,
		frameName:"castor.png",
		imageInit:["castor.png","castor1.png"],
		imageUp:["castor2.png","castor3.png"],
		imageDown:["castor6.png","castor7.png"],
		imageRotate:["castor.png","castor4.png","castor5.png"],
    }
];
var ObjectType = [
    {
    	type:0,
    	desplazamiento:20,
    	speed:10,
		moveType:BB.OBJECT_MOVE_TYPE.HORIZONTAL,
    	textureName:"sillon.png"
    },
    {
    	type:1,
    	desplazamiento:20,
    	speed:10,
		moveType:BB.OBJECT_MOVE_TYPE.HORIZONTAL,
    	textureName:"heladera.png"
    },
    {
        type:2,
        desplazamiento:20,
        speed:7,
        moveType:BB.OBJECT_MOVE_TYPE.ZICZAC,
        textureName:"tiburon.png"
    },
    {
        type:7,
        desplazamiento:20,
        speed:5,
        moveType:BB.OBJECT_MOVE_TYPE.ZICZAC,
        textureName:"piraña1.png"
    }
];